In [11]:
import tensorflow as tf
import numpy as np
import itertools

X = np.array(list(itertools.product([0, 1], repeat=4)), dtype=np.float32)

def logic_func(name, x):
    if name == "AND":
        return np.all(x == 1, axis=1).astype(np.float32)
    elif name == "OR":
        return np.any(x == 1, axis=1).astype(np.float32)
    elif name == "XOR":
        return (np.sum(x, axis=1) % 2).astype(np.float32)
    elif name == "NAND":
        return (1 - np.all(x == 1, axis=1)).astype(np.float32)
    elif name == "NOR":
        return (1 - np.any(x == 1, axis=1)).astype(np.float32)
    elif name == "XNOR":
        return (1 - (np.sum(x, axis=1) % 2)).astype(np.float32)
    else:
        raise ValueError("Unknown function")

func_name = "XOR"
y = logic_func(func_name, X)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(8, input_dim=4, activation='tanh'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.05),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.fit(X, y, epochs=300, verbose=0)

loss, acc = model.evaluate(X, y, verbose=0)
print(f"Функція: {func_name}")
print(f"Втрата: {loss:.6f}")
print(f"Точність: {acc:.4f}\n")

predictions = model.predict(X, verbose=0)
for inp, pred in zip(X, predictions):
    predicted_class = int(pred[0] >= 0.5)
    print(f"{inp.astype(int)} → {predicted_class} ({pred[0]:.4f})")


Функція: XOR
Втрата: 0.004251
Точність: 1.0000

[0 0 0 0] → 0 (0.0004)
[0 0 0 1] → 1 (0.9937)
[0 0 1 0] → 1 (0.9948)
[0 0 1 1] → 0 (0.0006)
[0 1 0 0] → 1 (0.9969)
[0 1 0 1] → 0 (0.0002)
[0 1 1 0] → 0 (0.0052)
[0 1 1 1] → 1 (0.9998)
[1 0 0 0] → 1 (0.9938)
[1 0 0 1] → 0 (0.0145)
[1 0 1 0] → 0 (0.0134)
[1 0 1 1] → 1 (0.9919)
[1 1 0 0] → 0 (0.0001)
[1 1 0 1] → 1 (0.9999)
[1 1 1 0] → 1 (0.9967)
[1 1 1 1] → 0 (0.0007)
